### ISSUE TITLE
Doesn't work on iOS devices if json contains base64 images

### ISSUE THREAD

**Issue by RomanTsarou** [alexzhirkevich/compottie#1]
Thanks for your job. You've made a great library.
I have a lottie animation with base64 images. It works properly on Android, but doesn't on iOS.

**Comment by alexzhirkevich** [comment]
This library doesn't implement lottie drawing. It only delegates it to the other renderers. If something doesn't work it means that this feature is not currently supported by this renderer

**Comment by LaatonWalaBhoot** [comment]
@alexzhirkevich can something like this be set for Skiko renderer https://github.com/airbnb/lottie-ios/issues/2314
It works with iOS. Android already works for me.

**Comment by alexzhirkevich** [comment]
Will be fixed with a [new multiplatform rendering engine](https://github.com/alexzhirkevich/compottie/pull/4)
