### ISSUE TITLE
[Bug]: DoLottie Not rendering on Android 7

### ISSUE THREAD

**Issue by Micoder-dev** [alexzhirkevich/compottie#11]
### What happened?

Recently I tested on an old Android device Redmi 5A it doesn't render.

### What Compottie version do you experience the bug on?

2.0.0-beta02

### What platforms are you seeing the problem on?

Android

**Comment by alexzhirkevich** [comment]
On Android <= N dotLottie module requires desugaring

https://developer.android.com/studio/write/java8-support#library-desugaring
