### ISSUE TITLE
[Bug]: Doesn't display base64 image on iOS

### ISSUE THREAD

**Issue by Dzertak** [alexzhirkevich/compottie#13]
### What happened?

Doesn't display animation where main image contains in base64 on iOS. But on Android it's work.

### What Compottie version do you experience the bug on?

1.1.2

### What platforms are you seeing the problem on?

iOS

**Comment by alexzhirkevich** [comment]
Images are supported starting with Compottie 2.0. Use `2.0.0-beta02`
