### ISSUE TITLE
[Bug]: component is not renederd

### ISSUE THREAD

**Issue by elad-nanit** [alexzhirkevich/compottie#16]
### What happened?

A rendering bug happened!

please look at the white X in the circle

<img width="668" alt="Screenshot 2024-08-05 at 17 06 19" src="https://github.com/user-attachments/assets/ad5c5bae-d852-4807-a3df-490439660a3f">

<img width="698" alt="Screenshot 2024-08-05 at 17 09 17" src="https://github.com/user-attachments/assets/53d69dc7-3094-4f39-8de2-c93b7f4999d8">

do you need the json file?

### Unsupported features

- [X] My animation doesn't use unsupported features

### What Compottie version do you experience the bug on?

2.0.0-beta02

### What platforms are you seeing the problem on?

Android

### Does Compottie log anythyng to the stdout / your logger set with `Compottie.logger`?

```shell
No
```

**Comment by alexzhirkevich** [comment]
>do you need the json file?

Yes. I can't say anything here without the animation file

**Comment by alexzhirkevich** [comment]
Closing this one. Please reopen if there would be updates or you will be able to share the animation file
