### ISSUE TITLE
[Bug]: The Animation display in the wrong color in 2.0.0-rc01

### ISSUE THREAD

**Issue by 658jjh** [alexzhirkevich/compottie#24]
### What happened?

For example with kind of animation like this:
https://lottiefiles.com/free-animation/gradient-loader-01-vC5xkkshyC
It displays like this: 
![Screenshot 2024-09-25 at 16 12 44](https://github.com/user-attachments/assets/dba22c60-5c68-4e45-89b0-0bac6195c08b)

### Unsupported features

- [ ] My animation doesn't use unsupported features

### What Compottie version do you experience the bug on?

2.0.0-rc01

### What platforms are you seeing the problem on?

Android

**Comment by alexzhirkevich** [comment]
This animation is using tint layer effect. It is not supported
