### ISSUE TITLE
Cant use Xcode 13 ( Compose 1.6.11 - requered Xcode 15 min

### ISSUE THREAD

**Issue by toffeantyri** [alexzhirkevich/compottie#26]
### What happened?

Compottie use compose 1.6.11 - can i fork compottie and use compose 1.6.10 ? 
Or compottie requered compose 1.6.11 Necessarily?

### What Compottie version do you experience the bug on?

last

### What platforms are you seeing the problem on?

iOS

**Comment by toffeantyri** [comment]
configurations.all { resolutionStrategy.eachDependency {
 if (requested.group == "compose" && requested.name == "compottie" && requested.version == "1.6.11") { useVersion("1.6.10") because("1.6.11 required Xcode 15") 
} } }

Смогу ли я повлиять на сборку таким образом?

**Comment by alexzhirkevich** [comment]
> configurations.all { resolutionStrategy.eachDependency { if (requested.group == "compose" && requested.name == "compottie" && requested.version == "1.6.11") { useVersion("1.6.10") because("1.6.11 required Xcode 15") } } }
> 
> Смогу ли я повлиять на сборку таким образом?

Да, можно так. Будет по-другому немного

```kotlin
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group.startsWith("org.jetbrains.compose") && requested.version == "1.6.11") {
          useVersion("1.6.10")
        }
    }
}
```
