### ISSUE TITLE
[Bug]: circle in pie chart is getting filled

### ISSUE THREAD

**Issue by elad-nanit** [alexzhirkevich/compottie#27]
### What happened?

A rendering bug happened!

you can see the bug in the first screenshot (the filled circle in the pie chart [donut chart]), it should look like as in the second screenshot (which uses `com.airbnb.lottie.compose.LottieAnimation`):

<img width="400" alt="Screenshot 2024-10-29 at 13 18 22" src="https://github.com/user-attachments/assets/30f97ad1-824d-48d0-b534-ca621815eb1f">

<img width="400" alt="Screenshot 2024-10-29 at 13 23 21" src="https://github.com/user-attachments/assets/0476eca3-c276-4ab4-88d1-7db46c199d14">

this is the lottie file:
[Dashboard.json](https://github.com/user-attachments/files/17556063/Dashboard.json)

P.S.
I use 2.0.0-beta02 version and I can't upgrade to 2.0.0-rc01 due to this error:
```
Your current Kotlin version is 1.9.23, while kotlinx.serialization core runtime 1.7.2 requires at least Kotlin 2.0.0-RC1. Please update your Kotlin compiler and IDE plugin.
```

### Unsupported features

- [ ] My animation doesn't use unsupported features

### What Compottie version do you experience the bug on?

2.0.0-beta02

### What platforms are you seeing the problem on?

Android

**Comment by alexzhirkevich** [comment]
Seems working fine with latest build. I'll publish fresh release soon with decreased serialization version

**Comment by elad-nanit** [comment]
> Seems working fine with latest build. I'll publish fresh release soon with decreased serialization version

Thank you very much, looking forward to it :pray:
