### ISSUE TITLE
Support dynamic properties

### ISSUE THREAD

**Issue by vcoolish** [alexzhirkevich/compottie#7]
something like this, otherwise theming doesn't work with animations
```
val properties = rememberLottieDynamicProperties(
    rememberLottieDynamicProperty(
        keyPath = arrayOf("**"),
        property = LottieProperty.COLOR,
        callback = { color.toArgb() }
    )
)
```

**Comment by alexzhirkevich** [comment]
This feature is coming with a new renderer - #4. You can view all upcoming features in the readme of the standalone branch

**Comment by vcoolish** [comment]
> This feature is coming with a new renderer - #4. You can view all upcoming features in the readme of the standalone branch

Sounds great! do you have a rough ETA to finilize that one?

**Comment by alexzhirkevich** [comment]
It's coming this week, but it will be the fist beta with potential bugs

**Comment by vcoolish** [comment]
Hi! Is the beta expected to start today?

**Comment by alexzhirkevich** [comment]
More likely tomorrow
