### ISSUE TITLE
Precomps doesn't work without provided assets manager

### ISSUE THREAD

**Issue by Vaibhav2002** [alexzhirkevich/compottie#8]
### What happened?

Some lottie animations are not rendered at all, all i see is a blank screen
Examples:
- [loading.json](https://github.com/user-attachments/files/16052229/loading.json)
- [splash.json](https://github.com/user-attachments/files/16052235/splash_dark.json)

### Unsupported features

- [X] My animation doesn't use unsupported features

### What Compottie version do you experience the bug on?

2.0.0-beta01

### What platforms are you seeing the problem on?

Android, iOS

**Comment by alexzhirkevich** [comment]
Reproduced. As a workaround you can provide any non-null assets manager to the painter:



```kotlin
object EmptyAssetsManager : LottieAssetsManager {
    override suspend fun image(image: LottieImage): ImageRepresentable? {
        return null
    }
}

val painter = rememberLottiePainter(
    ...
   assetsManager= EmptyAssetsManager
)
```
