### ISSUE TITLE
Support foreach dynamic properties manipulation

### ISSUE THREAD

**Issue by Vaibhav2002** [alexzhirkevich/compottie#9]
### What happened?

Changing color using dynamic properties is not working

### This is how i did previously in lottie-android
```kotlin
rememberLottieDynamicProperties(
    rememberLottieDynamicProperty(
        property = LottieProperty.COLOR,
        value = color.toArgb(),
        keyPath = listOf("Layer 1 Outlines 2", "**").toTypedArray()
    )
)
```

### This is how I'm doing it in compottie
```kotlin
rememberLottieDynamicProperties {
    shapeLayer("Layer 1 Outlines 2") {
        fill("**") { color { color } }
    }
}
```

### What Compottie version do you experience the bug on?

2.0.0-beta01

### What platforms are you seeing the problem on?

Android, iOS

**Comment by alexzhirkevich** [comment]
There is no support for ** currently. Only named fills

**Comment by Vaibhav2002** [comment]
@alexzhirkevich I tried this
```kotlin
layer("Layer 1 Outlines 2") {
    shapeLayer("Group 1"){
        fill("Fill 1") { color { color } }
    }
}
```

for animation 
[verified.json](https://github.com/user-attachments/files/16053089/verified.json)


But it still did not work

**Comment by alexzhirkevich** [comment]
It must be 
```kotlin
rememberLottieDynamicProperties {
    shapeLayer("Layer 1 Outlines 2") {
        fill("Group 1", "Fill 1") { color { Color.Red } }
    }
}
```

**Comment by alexzhirkevich** [comment]
layer(path) is a path to the layer
fill(path) is a path to the fill shape relative to the layer

**Comment by Vaibhav2002** [comment]
Thanks a lot, this did work
Would appreciate some documentation on using dynamic properties in Compottie

**Comment by sergeys-opera** [comment]
It would be really nice to get `**` work. Without the wildcard, you need to compose the full path to the layer which might be quite hard. A common use case is to get animation files from the UX team with instructions like "change the layer background color named XXX to some color" or "set a translation string for YYY layer".
